### ISSUE TITLE
GoLang RPC investigation

### ISSUE THREAD

**Issue by dotbugfix** [dotbugfix/GoNFS4#1]
Investigate how RPC calls are handled in GoLang. Also find out how XDR files (nfs4.x) can be converted to RPC stubs in GoLang.

**Comment by KaustubhDhokte** [comment]
Well, I just investigated 1st part of it. Creating a new task for XDR part.

**Comment by dotbugfix** [comment]
Can you add this issue # to your commit and close it out? I'd recommend a new 'Prototypes' directory in the master branch for investigative stuff (any better ideas for source code structure in our repo?)

**Comment by KaustubhDhokte** [comment]
Done. Commit 1f994e53448c3ec0f6861d01ce1ab32c63b512c0. Closing this.
Please reopen if you want to add/remove something or have any questions/suggestions.
